version: '3.1'

services:
  #proxy
  proxy:
    build:
      context: ./nginx/
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:8080"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
    networks:
      - proxy-net
networks:
  proxy-net:
    name: proxy_network